# Use root/example as user/password credentials
# version: 'jammy'

services:

  mongo:
    image: mongo:jammy
    restart: always
    ports:
      - 0.0.0.0:27017:27017
    volumes:
      - ${SMARTHOME_ROOT}/mongo_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
